spring.application.name=practica1
server.port=8080

# DataSource
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/springboot?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# No poner dialecto explícito, Hibernate 7 lo detecta automáticamente
